### ISSUE TITLE
Occluded text

### ISSUE THREAD

**Issue by splatboydev** [PressJump/reimaginedreadme#10]
The problem is as following, on https://myreadme.vercel.app/api/embed/splatboydev?panels=toprepositories
![image](https://user-images.githubusercontent.com/64037464/221739559-5a4a914b-e45f-400f-a2a4-1a946691e490.png)

The text is occluded (on the bottom) and cannot be fully read.

**Comment by PressJump** [comment]
Hey @splatboydev thanks for bringing this to my attention. Tagged as bug.

**Comment by PressJump** [comment]
Should be fixed on next build @splatboydev
Thanks for letting me know about this issue :).
