### ISSUE TITLE
My eyes beg you to add dark theme.

### ISSUE THREAD

**Issue by uhidontkno** [PressJump/reimaginedreadme#28]
[suggestion]

My eyes hate reimaginedreadme because its so bright compared to a dark mode README. Please add dark mode as a URL parameter. Me and my poor eyes beg you.

**Comment by uhidontkno** [comment]
Inverting the image already makes it 10x easier on the eyes. If you want to take the easy way out just invert the colors.

**Comment by IndexingGitHub** [comment]
https://github.com/PressJump/reimaginedreadme/pull/20#issuecomment-1907194277
