### ISSUE TITLE
Issue Count not updating

### ISSUE THREAD

**Issue by suhaanigurjar** [PressJump/reimaginedreadme#37]
The issues count does not update for some reason..
Maybe it's an error in the source or maybe I'm doing something wrong?

Could anyone explain?

![IMG_7767](https://github.com/user-attachments/assets/efdce41a-27c3-4fd1-9aee-4caea6f90c38)
![IMG_7766](https://github.com/user-attachments/assets/46aabdbb-79cb-4cee-b29d-d765b729c32f)

**Comment by PressJump** [comment]
Closed per #32
